INSERT INTO Brands(name,country) VALUES('Audi','Germany');
INSERT INTO Brands(name,country) VALUES('BMW','Germany');
INSERT INTO Brands(name,country) VALUES('Mercedes-Benz','Germany');
INSERT INTO Brands(name,country) VALUES('Volkswagen','Germany');
INSERT INTO Brands(name,country) VALUES('Porsche','Germany');
INSERT INTO Brands(name,country) VALUES('Ferrari','Italy');
INSERT INTO Brands(name,country) VALUES('Lamborghini','Italy');
INSERT INTO Brands(name,country) VALUES('Maserati','Italy');
INSERT INTO Brands(name,country) VALUES('Alfa Romeo','Italy');
INSERT INTO Brands(name,country) VALUES('Aston Martin','United Kingdom');
INSERT INTO Brands(name,country) VALUES('Bentley','United Kingdom');
INSERT INTO Brands(name,country) VALUES('Jaguar','United Kingdom');
INSERT INTO Brands(name,country) VALUES('Rolls-Royce','United Kingdom');
INSERT INTO Brands(name,country) VALUES('Volvo','Sweden');
INSERT INTO Brands(name,country) VALUES('Saab','Sweden');
INSERT INTO Brands(name,country) VALUES('Koenigsegg','Sweden');
INSERT INTO Brands(name,country) VALUES('Bugatti','France');
INSERT INTO Brands(name,country) VALUES('Renault','France');
INSERT INTO Brands(name,country) VALUES('Citroën','France');
INSERT INTO Brands(name,country) VALUES('Peugeot','France');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(1,'A6','1993');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(1,'A3','1993');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(1,'TT','1999');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(2,'3 Series','2018');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(2,'5 Series','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(3,'E-Class','2019');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(3,'C-Class','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(4,'Golf','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(4,'Passat','2019');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(5,'911','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(6,'458 Italia','2015');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(6,'F8 Tributo','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(7,'Huracán','2019');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(7,'Urus','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(8,'GranTurismo','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(9,'Giulia','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(10,'DBX','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(10,'Vantage','2019');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(11,'Continental GT','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(11,'Flying Spur','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(12,'F-Type','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(12,'XE','2018');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(13,'Phantom','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(13,'Ghost','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(14,'XC90','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(14,'S60','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(16,'Jesko','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(18,'Clio','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(18,'Megane','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(19,'C4','2019');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(19,'C3','2020');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(20,'208','2021');
INSERT INTO Cars(brand_id,name,year_of_manufacture) VALUES(20,'3008','2020');